logging:
  level:
    org:
      hibernate: debug
      springframework:
        web: debug
spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
  jpa:
    show-sql: true
  thymeleaf:
    cache: false # ?????????????????
  # 热部署生效
  devtools:
    restart:
      enabled: true
  # 设置需要重启的目录
      additional-paths: src/java/main
  # 设置不需要重启的目录
      exclude: static/**,public/**,WEB-INF/**
